name: Deploy to AlmaLinux

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server PROD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SRV_IP }}
          username: ${{ secrets.SRV_USERNAME }}
          key: ${{ secrets.SRV_SSHKEY }}
          script: |
            cd /usr/share/nginx/html
            git clone https://github.com/VillaviH/website-static.git
            mv website-static frontend
            systemctl restart nginx.service
            
      #- name: Clonar el repositorio
      #  run: git clone https://github.com/VillaviH/website-static.git
      #- name: Tareas post-clonación
       # run: |
        #  systemctl restart nginx.service
