name: Deploy to AlmaLinux

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     # - uses: actions/checkout@v3
      - name: Deploy to server
        uses: chux0519/zola-scp-action@1.1.0
        with:
          # Remote server address
          host:  ${{ secrets.SRV_IP }}
          # Remote server user
          user: ${{ secrets.SRV_USERNAME }}
          # Remote server private key
          key: ${{ secrets.SRV_SSHKEY }}
      - name: Clonar al repositorio
        run: git clone https://github.com/VillaviH/website-static.git /usr/share/nginx/html
      - name: Tareas post-clonación
        run: |
          systemctl restart nginx.service
