name: Deploy to AlmaLinux

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: Gabo-p/ssh-deploy-to-server@v1.0.7
        with:
          # Private key part of an SSH key pair
          SSH_PRIVATE_KEY: ${{ secrets.SRV_SSHKEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.SRV_IP }}
          # Remote user
          REMOTE_USER: ${{ secrets.SRV_USERNAME }}
      - name: Clonar el repositorio de trabajo
        run: git clone https://github.com/VillaviH/website-static.git /usr/share/nginx/html
      - name: Tareas post-clonación
        run: |
          systemctl restart nginx.service
