name: Deploy to AlmaLinux

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: ilCollez/ssh-scp-deploy@v1.3.0
        with:
          # Remote host
          host: ${{ secrets.SRV_IP }}
          # SSH remote user
          username: ${{ secrets.SRV_USERNAME }}
          # SSH private key
          key: ${{ secrets.SRV_SSHKEY }}
          # Remote destination path
      - name: Clonar al repositorio
        run: git clone https://github.com/VillaviH/website-static.git /usr/share/nginx/html
      - name: Tareas post-clonación
        run: |
          systemctl restart nginx.service
