name: Deploy to AlmaLinux

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 44.203.52.112
          username: hvillavicencio
          key: ${{ secrets.SRV_SSHKEY }}
          script: |
            cd /usr/share/nginx/html
      - name: Clonar el repositorio
        run: git clone https://github.com/VillaviH/website-static.git
      - name: Tareas post-clonación
        run: |
          systemctl restart nginx.service
