name: Deploy to AlmaLinux

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to server
        uses: invi5H/ssh-action@v1.0.0
        with: 
          # A unique name for the server
          NAME: ${{ secrets.SRV_IP }}
          # The SSH username
          SSH_USER: ${{ secrets.SRV_USERNAME }}
          # The hostname or the IP address
          SSH_HOST: ${{ secrets.SRV_IP }}
          # The full string SSH key
          SSH_KEY: ${{ secrets.SRV_SSHKEY }}
      - name: Clonar repositorio
        run: git clone https://github.com/VillaviH/website-static.git /usr/share/nginx/html
      - name: Tareas post-clonación
        run: |
          systemctl restart nginx.service
